/**
 * \file cfg_api_brick_mk3_types.h
 *
 * \brief Types used with the STAR-Dundee Brick Mk3 Configuration API.
 *
 * \author STAR-Dundee Ltd.\n
 *         STAR House\n
 *         166 Nethergate\n
 *         Dundee, DD1 4EE\n
 *         Scotland, UK\n
 *         e-mail: support@star-dundee.com
 *
 * Copyright &copy; 2013 STAR-Dundee Ltd.
 */

#ifndef CFG_API_BRICK_MK3_TYPES_H
#define CFG_API_BRICK_MK3_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

/**
 * \ingroup brickMk3Timestamping
 *
 * Timestamps can be generated by either an external trigger signal or by an 
 * internal pulse generator. This enum defines different methods of 
 * timestamping that are available.
 *
 * \versionAdded \ref changes_v3_6
 */
typedef enum
{
    /** No timestamp method */
    STAR_CFG_BRICK_MK3_TIMESTAMP_METHOD_NONE = 0,

    /** External trigger used for timestamp sync */
    STAR_CFG_BRICK_MK3_TIMESTAMP_METHOD_EXTERNAL_TRIGGER = 1,

    /** Internal pulse generator used for timestamp sync */
    STAR_CFG_BRICK_MK3_TIMESTAMP_METHOD_PULSE_GENERATOR = 2
} STAR_CFG_BRICK_MK3_TIMESTAMP_METHOD;

/**
 * \ingroup brickMk3Timestamping
 *
 * Defines frequencies that can be used by the global pulse generator.
 *
 * \versionAdded \ref changes_v3_6
 */
typedef enum
{
    /** 1Hz */
    STAR_CFG_BRICK_MK3_PULSE_FREQ_1 = 0,

    /** 10Hz */
    STAR_CFG_BRICK_MK3_PULSE_FREQ_10 = 1,

    /** 100Hz */
    STAR_CFG_BRICK_MK3_PULSE_FREQ_100 = 2,

    /** 1KHz */
    STAR_CFG_BRICK_MK3_PULSE_FREQ_1000 = 3
} STAR_CFG_BRICK_MK3_PULSE_FREQ;

#ifdef __cplusplus
}
#endif

#endif  /* CFG_API_BRICK_MK3_TYPES_H */
