# Makefile for the STAR-Dundee SpaceWire USB Driver

ifneq ($(KERNELRELEASE),)

	#EXTRA_CFLAGS += -Wall -Wextra
	#EXTRA_CFLAGS += -Wmissing-prototypes -Wmissing-declarations
	#EXTRA_CFLAGS += -pedantic

	ifdef DEBUG
		EXTRA_CFLAGS += -g -O0
	endif

	EXTRA_CFLAGS += -Os	# To get round a bug in __kfree_rcu in kernels > 2.6.39 

	obj-m := star_spw_usb.o
	star_spw_usb-objs := spwusb_driver.o spwusb_ioctl.o spwusb_fileops.o spwusb_datahandling.o \
						spwusb_buffers.o spwusb_kernel.o

else

	KDIR := /lib/modules/$(shell uname -r)/build
	PWD := $(shell pwd)
	INSTALLDIR := /lib/modules/$(shell uname -r)/kernel/drivers/spacewire

default:
	$(MAKE) -C $(KDIR) M=$(PWD) modules
	if [ ! -d "$(INSTALLDIR)" ]; \
	then mkdir -v -p "$(INSTALLDIR)"; \
	fi
	cp star_spw_usb.ko "$(INSTALLDIR)"

clean:
	/bin/rm -f *.o *.ko "$(INSTALLDIR)"\star_spw_usb.ko

endif
